### ISSUE TITLE
resource pattern does not end with brackets

### ISSUE THREAD

**Issue by xiaozhenliu-gg5** [googleapis/gapic-generator-typescript#215]
For resource like this:
```
  collections:
  - name_pattern: projects/{project}/agent
    entity_name: project_agent
  - name_pattern: projects/{project}/agents/{agent}
    entity_name: agent
```
```   
 this._pathTemplates = {
      agentPathTemplate: new gaxModule.PathTemplate(
        'projects/{project}/agents/{agent}'
      ),
      projectAgentPathTemplate: new gaxModule.PathTemplate(
        'projects/{project}/agent'
      ),
    };
```

we will generate just one
```
    this._pathTemplates = {
      agentPathTemplate: new gaxModule.PathTemplate(
        'projects/{project}/agent'
      ),
    };
```
